default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby3_development
  host: 172.17.0.2
  username: postgres
  password: 123456

test:
  <<: *default
  database: ruby3_test
  host: 172.17.0.2
  username: postgres
  password: 123456

